package: continuum-flask
user: ContinuumIO

platform:
  # - linux-32
  - linux-64
  # - win-32
  # - win-64
  # - osx-64

engine:
  - python=2

script:
  - conda build  ./conda.recipe/

build_targets: conda
