name: continuum-flask
dependencies:
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- markupsafe=0.23=py27_0
- mock=1.0.1=py27_0
- nose=1.3.4=py27_0
- openssl=1.0.1h=1
- pip=1.5.6=py27_0
- python=2.7.8=1
- readline=6.2=2
- setuptools=7.0=py27_0
- sqlite=3.8.4.1=0
- tk=8.5.15=0
- werkzeug=0.9.6=py27_1
- zlib=1.2.7=1
- pip:
  - blessings==1.6
  - gnureadline==6.3.3
  - ipdb==0.8
  - ipython==2.3.1
  - nose-progressive==1.5.1
  - wsgiref==0.1.2
